<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <!-- Bootstrap Min .css Link Below >>> -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD"
      crossorigin="anonymous"
    />
    <title>Try Catch Trhough</title>
  </head>
  <body>
    <h1 class="text-center py-4">Try-Catch-Trhough</h1>
    <main>
      <section id="container" class="container py-4">
        <div
          class="d-flex flex-column justify-content-center align-items-center"
        >
          <h1>Create custom error using Try and Catch</h1>
          <div class="py-4 d-flex w-50">
            <input
              class="w-75"
              type="text"
              id="age"
              placeholder="Enter age between 18-30"
            />
            <button onclick="checkAge()" type="submit">submit</button>
          </div>
          <p id="error"></p>
        </div>
      </section>
    </main>

    <!-- *My Scripts* -->
    <script src="./try-catch-through.js"></script>

    <!-- Bootstrap JS Link Below >>> -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
      crossorigin="anonymous"
    ></script>
  </body>
</html>
